spring:
  application:
    name: Config-Prod

eureka:
  instance:
    pref-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
